### ISSUE TITLE
Wrong Project template?

### ISSUE THREAD

**Issue by wildone** [totaljs/tms#2]
@petersirka this looks like FlowStream templarte?

I found another version https://github.com/totaljs/examples/tree/master/tms that seems to do the trick.

Also is there any examples how to use Postman with TMS?

**Comment by petersirka** [comment]
@wildone I don't use Postman, but it supports WebSocket then theoretically - yes. Also, TMS is targeted for Total.js apps only, so you can easily integrate multiple Total.js apps.

I don't know what you are using, but [Total.js Flow](https://github.com/totaljs/flow) supports everything together. In addition, Total.js FlowStream and TMS are our side projects prepared for various customizations.

**Comment by wildone** [comment]
@petersirka thanks for that, any specs on how to connect to TMS with "secret_tms" is it "x-token" as a header? 

This is what I have so far as config I've figured out.

url: ws://localhost:8000/$tms/

I have the TMS running as standalone service and have FlowSteams running as separate service as well. In FlowStreams I can connect and import scheama but when I send data to TMS nothing happens, hence I am looking at doing some direct testing with TMS.

This is what I have so far
![image](https://user-images.githubusercontent.com/170312/180120117-a754184a-735f-4903-8bd4-5af298d46584.png)

The codebase is here https://github.com/innovolve-ai/typerefinery/tree/develop/services

* [totaljs-flowstream](https://github.com/innovolve-ai/typerefinery/tree/develop/services/totaljs-flowstream) - will be the UI where flows are created, can be started using the flowstreams.bat, or just direct npm command, 
* [totaljs-messageservice](https://github.com/innovolve-ai/typerefinery/tree/develop/services/totaljs-messageservice) - will be a centralised API for all data, can be started using the messageservice.bat, or just direct npm command

**Comment by petersirka** [comment]
@wildone I have prepared a better example:

- [example.zip](https://github.com/totaljs/tms/files/9157165/example.zip)

__How to test it?__

- download & extract `example.zip` file
- run `app` in the form:
   - `cd app`
   - `node index.js 8001`
- run `flow` in the form:
   - `cd flow`
   - `node index.js 8000`
   - visit http://127.0.0.8000/
   - user: `admin`, pass: `admin`

**Comment by wildone** [comment]
@petersirka thank you, yours works and mine works now as well, just made sure names match across files.

![image](https://user-images.githubusercontent.com/170312/180590574-c22d55a1-93c5-4e28-bc22-7a612ce26879.png)

**Comment by wildone** [comment]
@petersirka you might want to push your example into this repo as well.
