### ISSUE TITLE
Python TMS Client Example?

### ISSUE THREAD

**Issue by wildone** [totaljs/tms#4]
Do your have any examples of how to post messages to TMS from python with token auth?

**Comment by petersirka** [comment]
Hi @wildone,
We don't have example :-( but with our support services, we can create an example with RAW WebSocket communication, and then you can easily copy the code to Python.

**Comment by wildone** [comment]
It would help TMS and TotalJs adoption to have examples in all common languages, otherwise you are blocked as it's not easy.

Are there any other open source projects currently trying to use TMS out of the goodness of their heart and love for open source?

**Comment by wildone** [comment]
Anyways I figured it out.
